### ISSUE TITLE
regeneratorRuntime is not defined in browser when regenerator: false in .babelrc 

### ISSUE THREAD

**Issue by tmacdonald** [single-spa/create-single-spa#112]
I have a fresh react install from `create-single-spa`. This defaults the .babelrc file to "regenerator": false.

When I add an async/await into my code, I get the following error in the browser, but not in the console:
`ReferenceError: regeneratorRuntime is not defined`

Note that this is when running `yarn start`.

**Comment by joeldenning** [comment]
Some notes about this:

What’s happening here is that babel compilies async / await down to use a thing called the “babel regenerator runtime,” which handles both generator functions and async/await. The regenerator runtime is sufficiently large that it is best for performance to only load it once in the browser.

There are several strategies for sharing the regenerator runtime:
1) Separate regenerator runtime per microfrontend
2) A single regenerator runtime in the root config that everyone uses

You can also configure babel regarding “how” to share it. A common way is to create and use a global variable called regeneratorRuntime. This is the default for many babel configurations. If we do it that way, we’d want to add the regenerator runtime to the root config and have it create that global var. Then all other microfrontends could call into that global variables.

Alternatively, we could have each microfrontend include its own regenerator runtime

**Comment by filoxo** [comment]
Should this be another configuration question when creating a root-config?

**Comment by joeldenning** [comment]
I think most people won't know how to answer the question - it's pretty deep in the weeds of configuration. I think it would be easiest just to choose a sane default and then implement that?

**Comment by filoxo** [comment]
I agree with that. Initially I'd assume it would be ideal to share the one in root config (with it being optionally created/included depending on browserslist? if that's even possible), along with updating the shared single-spa-webpack config that applications generated with c-s-s are using.

**Comment by joeldenning** [comment]
I don't know whether there is a way to optionally include files into a build based on browser target - that would be a good thing to look into. Here's the file that needs to be included:

https://unpkg.com/browse/regenerator-runtime@0.13.5/runtime.js

It creates the `regeneratorRuntime` global variable. The downside of sharing it in the root config is just if different microfrontends require different versions of the runtime. However, that can be solved by having the devianting microfrontends bundle in the regeneratorRuntime instead of use the shared one.

Perhaps easiest is to add the following to the root config's index.ejs?

```
<script nomodule src="https://cdn.jsdelivr.net/npm/regenerator-runtime@0.13.5/runtime.js"></script>
```

The `nomodule` attribute allows you to skip loading the script if you're in a browser that supports ES modules. The assumption there would be that any browser that supports ESM also supports async/await. Since both of those were in es6, I think it's likely that that assumption holds true. More info about `nomodule` at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

**Comment by joeldenning** [comment]
Oo we should use jsdelivr's "auto minify" feature to make it even smaller:

https://cdn.jsdelivr.net/npm/regenerator-runtime@0.13.5/runtime.min.js

**Comment by joeldenning** [comment]
Trying this out locally, `nomodule` doesn't work because that's based on which browser is being **used**, not which browser was targeted by preset-env.

**Comment by joeldenning** [comment]
Fix released in https://github.com/single-spa/create-single-spa/releases/tag/v1.8.0
