### ISSUE TITLE
Creating a single spa app in typescript has some problems

### ISSUE THREAD

**Issue by zanza00** [single-spa/create-single-spa#128]
Hi all,

I created both the root config and a react app with this tool in typescript and I found some problems.

- the tests don't work if you import something from another file 
	- this is because the correct transformer for jest should be `ts-jest`
- eslint display the error `  24:31  error  'X' is not defined no-undef` when using typescript specific type declaration (`type` and `interface`)
	- this one I didn't investigate too much I simply disabled lint in husky check

here is a repo created for the occasion https://github.com/zanza00/single-spa-testing-problem

I tried to fix the error by presenting a PR but I am not very familiar with the codebase and didn't found where to fix the issue, If someone is able to help me navigate the code I can do the PR myself.

**Comment by joeldenning** [comment]
Hi @zanza00, thanks for the clear bug report. I have created https://github.com/zanza00/single-spa-testing-problem/pull/1 to show how to fix the issue with the tests, and will also put together a fix to create-single-spa for this.

> the tests don't work if you import something from another file. this is because the correct transformer for jest should be ts-jest

We are using `@babel/preset-typescript`, not typescript, for compilation of the types. As such, using babel-jest is the correct behavior. Here is the explanation of the issue:

1. jest is using babel to compile the code
2. babel was compiling the code to es5 / ie11 format when running the tests
3. To help with compilation, babel was calling require('@babel/runtime/helpers/<name-of-helper>')
4. Babel runtime was in ES module format instead of CJS. Jest does not yet support ES modules.

The fix is to tell babel to use "current node" as a target during tests, sincec the current version of node has many more features than IE11. This avoids the need to use the babel runtime helpers during the tests, which avoids the ES module issue. You can see this at https://github.com/zanza00/single-spa-testing-problem/pull/1/files#diff-e56633f72ecc521128b3db6586074d2cR22.

> eslint display the error 24:31 error 'X' is not defined no-undef when using typescript specific type declaration (type and interface)

I was unable to reproduce this problem - see [here](https://github.com/zanza00/single-spa-testing-problem/pull/1/files#diff-c5471de5af24465398a3fc4792dcb8e5R8) where I added some types and the linter didn't fail on them.

**Comment by zanza00** [comment]
Thanks for the PR and explanation 😄, it's more clear what is the problem, I am not too familiar with babel because before the introduction to single-spa we would use tsc directly.

For the tests, I would like to work on a PR tomorrow to fix the issue.

For eslint I will try to replicate the problem since the project in which occurs has a lot more types.

**Comment by joeldenning** [comment]
> For the tests, I would like to work on a PR tomorrow to fix the issue.

I already created a pull request for this at https://github.com/single-spa/create-single-spa/pull/129. Apologies for not giving you the chance to dive into it - we welcome new contributors as much as possible. In this case, I had a few mins and put together the fix before I saw that you had volunteered to do it. Perhaps you could take a look at #129 and leave any feedback that you might have on it?

> For eslint I will try to replicate the problem since the project in which occurs has a lot more types.

Sounds good.
