### ISSUE TITLE
Alternative for those not using org-scoped packages

### ISSUE THREAD

**Issue by mellis481** [single-spa/create-single-spa#159]
create-single-spa is somewhat opinionated in the convention it uses for the microfrontend name, file names, etc.. For my team, the file name (`orgName-projectName`) is a non-issue, but we're not using org-scoped packages (`@orgName/projectName`).  For those in my same boat, can create-single-spa be updated to not use org-scoped packages if an `orgName` is not entered during the setup process?

If so, I can work on a PR.

**Comment by joeldenning** [comment]
I'm not opposed to people using a different naming convention for their microfrontends. One reason that the `@org/project` convention is used in this project is that it makes it so that we can easily set up webpack externals properly:

https://github.com/single-spa/create-single-spa/blob/383ca77d79c24ca624564de43a75982b68fc0846/packages/webpack-config-single-spa/lib/webpack-config-single-spa.js#L75

If there is no `@org/` prefix to the microfrontend names, this will stop working. I'm open to adding an option to single-spa that disables this behavior in the CLI and also in webpack-config-single-spa, if that's desireable. Perhaps in the Yeoman generators it would be a variable `this.options.useOrgScope` and then in webpack-config-single-spa it would only add the webpack externals if `orgName` is provided.

**Comment by filoxo** [comment]
https://github.com/single-spa/create-single-spa/pull/199 adds the ability to disable the org scope through the webpack config released in [v1.16.0](https://github.com/single-spa/create-single-spa/releases/tag/v1.16.0).
