### ISSUE TITLE
Add pnpm

### ISSUE THREAD

**Issue by rajasegar** [single-spa/create-single-spa#211]
Add pnpm to the list of package managers to choose
https://pnpm.js.org

**Comment by joeldenning** [comment]
I'd like to add support for this. We are using yeoman/generator to help manage the dependencies, and it currently doesn't support pnpm. See the following code:

https://github.com/yeoman/generator/blob/9cd93ee0fe8babd26cce4e22a6f1db7637573801/lib/actions/install.js#L119

It looks like yeoman generator has an old, but open PR for this at https://github.com/yeoman/generator/pull/1067. It seems that they didn't merge it because they didn't consider pnpm popular enough in 2018 to justify it. I think that we could try to revive the discussion - in 2020 I think pnpm is more popular than it was previously.

**Comment by rajasegar** [comment]
Thanks @joeldenning , let's hope they merge it soon...

**Comment by joeldenning** [comment]
I implemented a workaround for this in #263

**Comment by rajasegar** [comment]
Really excited to have pnpm support :+1:

**Comment by joeldenning** [comment]
Released in https://github.com/single-spa/create-single-spa/releases/tag/v2.2.0
