### ISSUE TITLE
Solved: Can't get realtime (hot) updates on parcels in root-config

### ISSUE THREAD

**Issue by tr4g** [single-spa/create-single-spa#240]
**Describe the bug or question**
When you work with Vue 2 or other framework development server, you get instant updates in your browser as you save changes, but that wasn't working in root-config for parcels.

**To Reproduce**
Create a project with vue CLI, then add it to a root-config parcel project, and try editing something on one of your parcels

**Expected behavior**
The browser should reflect your change, but you have to reload it to see it. And you get the following console error:
```
Refused to connect to 'http://172.25.112.109:8080/sockjs-node/info?t=1608128575739' because it violates the following Content Security Policy directive: "connect-src https: localhost:* ws://localhost:*".
```

** SOLUTION **
Disable CSP for local development
Line 20:
```html
  <% if (!isLocal) { %>
    <meta http-equiv="Content-Security-Policy" content="default-src 'self' https: localhost:*; script-src 'unsafe-inline' 'unsafe-eval' https: localhost:*; connect-src https: localhost:* ws://localhost:*; style-src 'unsafe-inline' https:; object-src 'none';">
  <% } %>
```

**Comment by joeldenning** [comment]
I transferred this issue to create-single-spa. The Content-Security-Policy inside of the create-single-spa root config is intended to be modified by everyone who uses security, as we cannot make effective security decisions on behalf of every user. You should modify the Content-Security-Policy to suit your needs, by adding `ws://172.25.112.109` and `http://172.25.112.109` to the `connect-src` in your index.ejs file. If that doesn't work, try variations of that until you find something that works. I'd also recommend reading the documentation for Content-Security-Policy to find what additions to your CSP are necessary, since CSP a browser standard that's unrelated to single-spa.

https://www.google.com/search?q=mdn+content+security+policy&rlz=1C5CHFA_enUS869US869&oq=mdn+content+security+po&aqs=chrome.0.0i457j69i57.2215j1j4&sourceid=chrome&ie=UTF-8

It wouldn't make sense for us to add `172.25.112.109` to create-single-spa code, since it is an IP address that's not commonly used for local development (t's a public IP address in Salt Lake City).
