### ISSUE TITLE
The resolved extensions order is problematic when using graphql client

### ISSUE THREAD

**Issue by sergioflores-j** [single-spa/create-single-spa#241]
Hey folks, awesome work on this project! It helps a lot to bootstrap a single-spa application :D

Just to let you know I've had a problem with the default webpack configuration while using **GraphQL client**.
More info about the issue: https://github.com/graphql/graphql-js/issues/1272

Here's the [problematic line](https://github.com/single-spa/create-single-spa/blob/25f953c5ea09731c39a04770ce1d5854886e3e16/packages/webpack-config-single-spa/lib/webpack-config-single-spa.js#L125
), if you change the `.mjs` and `.js` order, everything works fine!

I've managed to fix this on my webpack.config, but it's better to have it fixed here 'cause someone else can run into this.

**Comment by filoxo** [comment]
Very interesting, thank you for sharing that info with us! I found https://github.com/graphql/graphql-js/issues/1272 that explains further why its needed. I think we can definitely make this change. Do you want to contribute that fix? Otherwise one of us can tackle it soon but perhaps not immediately.

**Comment by filoxo** [comment]
This is released in webpack-config-single-spa@1.18.3. Thanks again!
