### ISSUE TITLE
Add Ember to the framework options on create-single-app

### ISSUE THREAD

**Issue by PazAutumn** [single-spa/create-single-spa#268]
I'm looking forward to use single-spa but my main project uses ember and is not in the options, it would be nice to add it for making the process more easy. thank you!

**Comment by joeldenning** [comment]
There isn't a lot of ember expertise in the single-spa core team, so this one might be tricky. In the past, Ember has been a bit tricky to support. @rajasegar has done a fair amount of work for supporting Ember, though, including [this example](https://github.com/multi-ember-mfe). Perhaps he could help guide what ember support in create-single-spa would look like

**Comment by rajasegar** [comment]
@PazAutumn Ember is really not a conducive framework for creating Micro-Frontends because of a lot of reasons. The main one being the usage of a lot of global variables for storing app context like window.Ember, loader, require, define and so on. Having been working on this for a long time I came to this conclusion and I am pushing to move away from Ember at work to a more Micro-Frontend friendly frameworks like React, Vue, etc., I link some of the resources likes blog posts, examples and issues I have been dealing with Ember and single-spa in the past so that some one who is treading down the same road as me will move in the right direction:
https://github.com/ember-cli/loader.js/issues/204
https://github.com/rajasegar/multi-ember-app
https://github.com/ember-cli/ember-resolver/issues/629
https://dev.to/rajasegar/ember-micro-frontends-with-single-spa-1p8j
Having said that we are actually building micro-frontends with multiple Ember apps at work with a lot of hacks like reloading the pages for different Ember apps so that they work properly due to the fact that at any point of time only one Ember app can work properly in the browser unless you put the other one inside an iframe or something. Our microfrontend structure looks like we have 2 React apps and 2 Ember apps but it is not a SPA experience as I said earlier because of the constraints from Ember.

**Comment by PazAutumn** [comment]
Thank you @rajasegar for your arguments, you gave me a lot to think of.
