### ISSUE TITLE
webpack-dev-server v4.0.0-beta.0 not needed

### ISSUE THREAD

**Issue by nilzona** [single-spa/create-single-spa#270]
I have noticed that if I create a react single-spa application with create-single-spa it will setup my project with webpack-dev-server v4.0.0-beta.0.

If I modify package.json so that `webpack-dev-server` is the LTS like e.g. 3.11.2 it stops working with the error
```
Uncaught Error: application '@qmfe/sspa-react2' died in status LOADING_SOURCE_CODE: "does not export a unmount function or array of functions"
    at transformErr (app-errors.js:87)
    at handleAppError (app-errors.js:6)
    at load.js:113
```

BUT, if I modify the webpack.config.js and add `target: ['web']` it works again. Just a heads up that's the case. Maybe it should be used instead of a beta.

**Comment by joeldenning** [comment]
Since we're already on webpack-dev-server@4, I'd rather not go back. The reason we upgraded to v4 is that we were encountering [this bug](https://github.com/webpack/webpack-dev-server/issues/2484), which was only fixed in webpack-dev-server@4 via https://github.com/webpack/webpack-dev-server/pull/2839.

webpack-dev-server@4.0.0-beta.0 has some problems related to the watcher that have been fixed, but not yet released. Other than that, though, I do not know of any major bugs with webpack-dev-server@4. Are you unable to use webpack-dev-server@4? What is the problem with it?

**Comment by nilzona** [comment]
hey @joeldenning. I haven't found any major issues except that you will have to swap around some settings regarding https and that the logs look funny :)
I'm just somewhat concerned that the beta has been out for quite a long time without any updates on it, whereas the @3 track is still moving with fixes.  But hopefully it will start moving again soon enough.

**Comment by joeldenning** [comment]
We're working on improved TLS support in #267. The maintainers of webpack-dev-server have said they've been busy recently but still are planning on releasing beta 1
