### ISSUE TITLE
webpack-config-single-spa@2.2.0 breaks Vue based root project

### ISSUE THREAD

**Issue by ryanatball** [single-spa/create-single-spa#277]
I now get this error:

[webpack-cli] Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
Make sure the rule matching .vue files include vue-loader in its use.
    at VueLoaderPlugin.apply (/cosmos/plugins/cosmosc2-tool-base/node_modules/vue-loader/lib/plugin-webpack5.js:93:13)
    at createCompiler (/cosmos/plugins/cosmosc2-tool-base/node_modules/webpack/lib/webpack.js:69:12)
    at create (/cosmos/plugins/cosmosc2-tool-base/node_modules/webpack/lib/webpack.js:113:15)
    at webpack (/cosmos/plugins/cosmosc2-tool-base/node_modules/webpack/lib/webpack.js:121:46)
    at WebpackCLI.f [as webpack] (/cosmos/plugins/cosmosc2-tool-base/node_modules/webpack/lib/index.js:39:15)
    at WebpackCLI.createCompiler (/cosmos/plugins/cosmosc2-tool-base/node_modules/webpack-cli/lib/webpack-cli.js:1847:29)
    at async WebpackCLI.buildCommand (/cosmos/plugins/cosmosc2-tool-base/node_modules/webpack-cli/lib/webpack-cli.js:1954:20)
    at async Command.<anonymous> (/cosmos/plugins/cosmosc2-tool-base/node_modules/webpack-cli/lib/webpack-cli.js:735:25)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/cosmos/plugins/cosmosc2-tool-base/node_modules/webpack-cli/lib/webpack-cli.js:1284:13)

Downgrading to webpack-config-single-spa@2.1.1 works again.

Here is the webpack config:

https://github.com/BallAerospace/COSMOS/blob/master/cosmos-frontend-init/cosmosc2-tool-base/webpack.config.js

**Comment by joeldenning** [comment]
I am busy for the next day or two, but will look at this after.

**Comment by ryanatball** [comment]
Thanks Joel, appreciate it.   I've looked at the diffs between your two releases and don't understand what would cause this.

**Comment by joeldenning** [comment]
The link above is no longer working - can you provide a new one?

**Comment by ryanatball** [comment]
https://github.com/BallAerospace/COSMOS/blob/master/cosmos-frontend-init/cosmosc2-tool-base/webpack.config.js

**Comment by ryanatball** [comment]
Can also confirm that the same error still occurs

**Comment by joeldenning** [comment]
This is a bug in vue-loader. The reason why it only surfaced once you upgraded webpack-config-single-spa  is that https://github.com/single-spa/create-single-spa/pull/276 adds a new webpack `module.rules` object that surfaces the bug in vue-loader.

The bug is that vue-loader considers the following webpack module.rule object to be a "vue rule".

```js
  {
    test: /\.(bmp|png|svg|jpg|jpeg|gif|webp)$/i,
    exclude: /node_modules/,
    type: 'asset/resource'
  },
```

The reason is that vue-loader's RuleSetCompiler doesn't properly handle the new webpack 5 `asset/resource` rule type. See https://webpack.js.org/guides/asset-management/#loading-images which shows that webpack-config-single-spa's rule is valid. And see https://github.com/vuejs/vue-loader/blob/b53ae44e4b9958db290f5918248071e9d2445d38/lib/plugin-webpack5.js#L58 for the line of code in vue's webpack 5 plugin that errantly considers the valid rule object to be a vue rule. I confirmed this by putting console.log's into vue-loader and seeing that the vueRules array is being set to `[ { type: 'type', value: 'asset/source' } ]`.

I wasn't able to find an existing issue in vue-loader for this, so the next step would be to create one. However, since this isn't the fault of create-single-spa, I'll leave that to you to do.

**Comment by ryanatball** [comment]
Are you sure?  This broke on Monday with the 2.2.0 release.  It looks like you just merged #276 an hour ago?

**Comment by ryanatball** [comment]
This was the change from 2.2.0 I think:

```
        {
          test: /\.html$/i,
          exclude: /node_modules/,
          use: [require.resolve("raw-loader", { paths: [__dirname] })],
        },
```

It's not using asset/resource

**Comment by ryanatball** [comment]
Confirmed that if I remove those lines, it builds again.

**Comment by ryanatball** [comment]
A believe the root cause is vue loader wants to be associated to any rules that match foo.vue.html (which this rule does)

**Comment by joeldenning** [comment]
Ah yes good catch I was looking at the wrong code change. It seems that the problem is still the same, though - vue-loader thinks it should be in charge of all `.html` files, which is not how webpack-config-single-spa. Using vue-loader with webpack-config-single-spa is not very common, since create-single-spa doesn't ever generate that. However, if you want to get it to work you can remove the rule for `.html` files via webpack-merge.

**Comment by ryanatball** [comment]
I came up with a solution using webpack-merge.  Thanks for pointing me in the right direction.
