### ISSUE TITLE
CORS issue with Swapi API

### ISSUE THREAD

**Issue by protoEvangelion** [single-spa/create-single-spa#69]
Getting this error when generating a react application & when going directly to the example react microfrontend: https://react.microfrontends.app/people

![image](https://user-images.githubusercontent.com/20076677/78902387-954a9a00-7a2e-11ea-9f40-fde4a7ed2a5f.png)

I'm not sure if the SWAPI api is down or if it's actually a CORS issue.

When navigating to the swapi docs page or api, it looks like a blank heroku site:
 
https://swapi.co/documentation

**Comment by joeldenning** [comment]
Hi @protoEvangelion, this is due to Content-Security-Policy. See https://github.com/single-spa/create-single-spa/pull/44 and [this documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP). If you would rather not deal with CSP and just want things to work, you can comment out or remove the content security policy.

https://github.com/single-spa/create-single-spa/blob/646092d6e2649716c799fd09c6e6eda91eaf317b/packages/generator-single-spa/src/root-config/templates/src/index.ejs#L8-L12

cc @filoxo, who authored this. I am closing this issue because there is no bug here. But feel free to comment further or reopen.

**Comment by protoEvangelion** [comment]
@joeldenning Thanks for the docs & explanation. There is no CSP meta tag though in the demo repo: https://github.com/react-microfrontends/root-config/blob/master/src/index.ejs 

![image](https://user-images.githubusercontent.com/20076677/78946043-94d5f180-7a76-11ea-8b4c-ecb6b306c0f2.png)

Not a huge deal but it would be nice if the recommended demo repo worked for newcomers like myself :)

**Comment by joeldenning** [comment]
Oops I misread this! This is a CORS error, not CSP!

There is nothing that we could do to make the swapi API work with CORS.

**Comment by joeldenning** [comment]
You can read more about CORS at https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS - it is something that is implemented by the browser, not single-spa.

**Comment by filoxo** [comment]
Actually, this appears to just be that swapi is no longer working. The readme even says that it's no longer maintained: 
https://github.com/phalt/swapi

**Comment by joeldenning** [comment]
Oh haha good catch I didn’t even realize that  it was *our* code calling swapi. This must have stopped working recently.

I’ve been wrong a couple times on this. Yes let’s fix this - I see you create an issue over in the example repo.
