### ISSUE TITLE
Add “update-deps” script in root directory package json 

### ISSUE THREAD

**Issue by joeldenning** [single-spa/create-single-spa#84]
This would call upgrade-interactive in every package.json it could find, including template package jsons

**Comment by filoxo** [comment]
I looked into this. It seems that upgrade-interactive isn't going to be good enough. When I tried `lerna exec --concurrency 1 -- yarn upgrade-interactive` the output does not give you any indication as to which package is being updated. 

![Screen Shot 2020-05-26 at 9 51 29 AM](https://user-images.githubusercontent.com/4202993/82922424-d0e5e880-9f36-11ea-9dbf-eb712b4f6347.png)

Similarly, there is no indication as to which package errored if one does.

![Screen Shot 2020-05-26 at 9 54 53 AM](https://user-images.githubusercontent.com/4202993/82922581-02f74a80-9f37-11ea-8115-37efbaebaca9.png)

I started looking around and came across [lerna-update-wizard](https://www.npmjs.com/package/lerna-update-wizard) which looked interesting. I tried it out and it works but it runs `yarn install <package>` on every lerna package for every npm package to update, which makes it slow. Maybe that is acceptable since it shouldn't need to happen very often? 

![Screen Shot 2020-05-26 at 11 08 43 AM](https://user-images.githubusercontent.com/4202993/82929692-51114b80-9f41-11ea-9f70-915447ca0121.png)

**Comment by joeldenning** [comment]
I did this manually in #226 - I don't think this process has to be automated as long as the manual way isn't too complicated. Here are the steps:

1. Install `ncu`
2. Find all the package.jsons
```sh
find . -not -path "*node_modules*" | grep package.json
```
3. `cd` into each of the directories that contain a package.json. Then run `ncu -i`
4. Find all `index.ejs` files (there are only two)
5. Manually go through the file and upgrade all `<script>` and other places where dependencies are loaded.
