### ISSUE TITLE
Entry point with arbitrary name in web pack-config-single-spa-react

### ISSUE THREAD

**Issue by ccozad** [single-spa/create-single-spa#88]
Hi thank you for creating this awesome project. I am having some trouble adapting an existing react project to work within single-spa. The directory structure is different than a typical project generated from create-react app. This means the web pack-config-single-spa-react helper is not able to find my entry point when I specify orgName and projectName.

Would you please consider adding an "entryPointFullPath" or similar parameter to allow the exact path to be specified? The behavior I would like to see is the current behavior we have today and when the fullPath option is provided that value is used instead of the constructed name.

**Comment by joeldenning** [comment]
Hi @ccozad - you can change the entry point using webpack-merge. Inside of your project, create-single-spa creates a webpack.config.js file that you can modify. Here's how you can change the entry:

```js
// webpack.config.js
const path = require('path')
const webpackMerge = require("webpack-merge");
const singleSpaDefaults = require("webpack-config-single-spa-react")

module.exports = (webpackConfigEnv) => {
  const defaultConfig = singleSpaDefaults({
    orgName: "example-org",
    projectName: "example-project",
    webpackConfigEnv,
  });

  return webpackMerge.strategy({
    entry: 'replace'
  })(defaultConfig, {
    // modify the webpack config however you'd like to by adding to this object
    entry: path.resolve(__dirname, 'src/some-other-entry.js')
  });
};
```

More details at https://github.com/survivejs/webpack-merge.

I am closing this since this is already possible, but feel free to comment further or reopen.
